// models.js — All 151 MEM management models with full metadata

const CATEGORIES = [
  "Action & Execution",
  "Perception & Thinking",
  "Motivation & Behavior",
  "Change Management",
  "Communication",
  "Decision & Problem Solving",
  "Planning & Priorities",
  "Delegation & Management",
  "Hiring, Training & Performance",
  "Organization, Economics & Systems"
];

const MODELS = [
  {
    number: 1,
    name: "Acres of Diamonds",
    meaning: "Look for the next opportunity in your current situation first before seeking outside solutions.",
    example: "Before buying a new CRM, fix the broken handoff already inside the current one.",
    category: "Action & Execution",
    trigger: "Use when tempted to seek external solutions before fully mining internal opportunities.",
    diagnosticQuestion: "Have I fully explored what is available within my current situation before looking elsewhere?",
    relatedModels: [80, 91, 39, 38],
    comments: ""
  },
  {
    number: 2,
    name: "Action Path",
    meaning: "Use an action already inside your authority that advances objectives.",
    example: "A supervisor changes the escalation script without waiting for executive approval.",
    category: "Action & Execution",
    trigger: "Use when progress is stalled waiting for permission — identify what you can do right now within your authority.",
    diagnosticQuestion: "What action within my current authority can I take right now to advance this objective?",
    relatedModels: [3, 69, 8, 70],
    comments: ""
  },
  {
    number: 3,
    name: "Action T.N.T.",
    meaning: "Action today, not tomorrow.",
    example: "A service leader resolves a recurring approval delay the same afternoon it is exposed.",
    category: "Action & Execution",
    trigger: "Use when there is a tendency to defer important actions that could be taken immediately.",
    diagnosticQuestion: "What am I postponing that I could resolve or advance today?",
    relatedModels: [2, 96, 70, 111],
    comments: ""
  },
  {
    number: 4,
    name: "Activity Avoidance",
    meaning: "Low-priority work becomes a refuge from high-priority work.",
    example: "Polishing slides instead of addressing a failing client account.",
    category: "Action & Execution",
    trigger: "Use when someone (including yourself) seems busy but important priorities are not moving.",
    diagnosticQuestion: "Is the current activity the highest priority, or is it avoiding the harder, more important work?",
    relatedModels: [38, 110, 96, 142],
    comments: ""
  },
  {
    number: 5,
    name: "Algebraic Results",
    meaning: "Results are the sum of positive and negative contributions.",
    example: "A launch with strong revenue but huge rework is not a clean win.",
    category: "Decision & Problem Solving",
    trigger: "Use when evaluating outcomes — look at the full ledger of positives and negatives, not just the headline.",
    diagnosticQuestion: "What are the hidden negative contributions that offset the apparent positive results?",
    relatedModels: [116, 137, 91, 143],
    comments: ""
  },
  {
    number: 6,
    name: "Ambivalence",
    meaning: "Mixed, often opposite, feelings about a person or situation.",
    example: "A manager supports a promotion but resents losing top talent.",
    category: "Motivation & Behavior",
    trigger: "Use when someone's behavior seems contradictory — look for competing emotional pulls.",
    diagnosticQuestion: "What opposing feelings might be driving this person's contradictory behavior?",
    relatedModels: [68, 47, 115, 85],
    comments: ""
  },
  {
    number: 7,
    name: "Answers in Search of Questions",
    meaning: "What you know shapes which problems you notice and how you try to solve them.",
    example: "A finance lead frames churn as a pricing issue because that is the toolkit he knows.",
    category: "Perception & Thinking",
    trigger: "Use when solutions seem predetermined — check whether the problem definition is being shaped by existing expertise.",
    diagnosticQuestion: "Is this problem being defined by the available solution rather than the actual situation?",
    relatedModels: [9, 65, 99, 122],
    comments: ""
  },
  {
    number: 8,
    name: "Anxiety Streams",
    meaning: "Anxiety often flows from guilt, mortality, and purpose concerns.",
    example: "Reorganization resistance reflects fear of lost meaning, not just extra work.",
    category: "Motivation & Behavior",
    trigger: "Use when resistance to change seems disproportionate — look for deeper psychological sources.",
    diagnosticQuestion: "What deeper concerns about identity, meaning, or security might be driving this resistance?",
    relatedModels: [85, 97, 21, 6],
    comments: ""
  },
  {
    number: 9,
    name: "Army Game",
    meaning: "People do only what they are explicitly told.",
    example: "An analyst sees a reporting error and waits instead of fixing or escalating it.",
    category: "Delegation & Management",
    trigger: "Use when people are not showing initiative — check if expectations for proactive behavior have been clearly set.",
    diagnosticQuestion: "Have I explicitly communicated what initiative and ownership look like in this role?",
    relatedModels: [33, 34, 151, 18],
    comments: ""
  },
  {
    number: 10,
    name: "Aspirin Doctor",
    meaning: "People prescribe solutions within their own expertise.",
    example: "IT proposes software for a process-discipline problem.",
    category: "Perception & Thinking",
    trigger: "Use when a proposed solution seems to fit the solver's expertise more than the actual problem.",
    diagnosticQuestion: "Is this solution shaped by the proposer's toolkit rather than the nature of the problem?",
    relatedModels: [7, 65, 32, 130],
    comments: ""
  },
  {
    number: 11,
    name: "Attitude Box",
    meaning: "Responses depend on attitudes shaped by experience and environment.",
    example: "The same policy is welcomed by one team and resisted by another.",
    category: "Motivation & Behavior",
    trigger: "Use when the same message produces very different responses from different people or teams.",
    diagnosticQuestion: "What past experiences or environmental factors are shaping this person's attitude toward this situation?",
    relatedModels: [12, 97, 132, 122],
    comments: ""
  },
  {
    number: 12,
    name: "Attitude Stair-Steps",
    meaning: "Change in action follows staged change in attitude: awareness, understanding, concern, dissatisfaction, action.",
    example: "A leader first builds understanding before asking teams to adopt a new workflow.",
    category: "Change Management",
    trigger: "Use when a change initiative is failing — diagnose which attitude step people are stuck on.",
    diagnosticQuestion: "Are people aware, do they understand, are they concerned, are they dissatisfied, and are they ready to act?",
    relatedModels: [36, 87, 20, 56],
    comments: ""
  },
  {
    number: 13,
    name: "Authority Syndrome",
    meaning: "'I lack authority' becomes an excuse for nonperformance.",
    example: "A manager complains about a bottleneck instead of escalating it with options.",
    category: "Action & Execution",
    trigger: "Use when someone claims they cannot act due to lack of authority — check if action within current authority is possible.",
    diagnosticQuestion: "What action within current authority would advance this situation, even partially?",
    relatedModels: [2, 9, 33, 107],
    comments: ""
  },
  {
    number: 14,
    name: "Behavior Is Goal Directed",
    meaning: "Behavior usually serves a goal.",
    example: "A rep discounts heavily to hit quarter-end quota.",
    category: "Motivation & Behavior",
    trigger: "Use when behavior seems irrational — identify what goal it is actually serving.",
    diagnosticQuestion: "What goal is this behavior serving, even if it appears counterproductive from the outside?",
    relatedModels: [90, 83, 36, 85],
    comments: ""
  },
  {
    number: 15,
    name: "Borrowed Perception",
    meaning: "Much of what we 'know' comes from others' perceptions.",
    example: "A new hire judges a department from hallway stories before working with it.",
    category: "Perception & Thinking",
    trigger: "Use when evaluating opinions — determine if views are firsthand or absorbed from others.",
    diagnosticQuestion: "Is this belief based on direct experience or adopted from someone else's perception?",
    relatedModels: [122, 99, 132, 150],
    comments: ""
  },
  {
    number: 16,
    name: "Boss Interpreter",
    meaning: "Someone becomes the unofficial decoder of leadership intent.",
    example: "Staff go to the chief of staff to interpret the CEO's remarks.",
    category: "Communication",
    trigger: "Use when communication from leadership is creating confusion — identify who is interpreting the message and whether that's a problem.",
    diagnosticQuestion: "Is there an unofficial interpreter between leadership and staff, and is that person accurate?",
    relatedModels: [22, 77, 23, 88],
    comments: ""
  },
  {
    number: 17,
    name: "Business-Owner Concept",
    meaning: "Run your unit like a business within the business.",
    example: "A warehouse manager tracks cost, quality, service, and inventory turns as if owning the operation.",
    category: "Delegation & Management",
    trigger: "Use when a team or unit lacks accountability — encourage full ownership of outcomes, not just task completion.",
    diagnosticQuestion: "Is this person or team taking full ownership of results, or just executing assigned tasks?",
    relatedModels: [71, 38, 28, 94],
    comments: ""
  },
  {
    number: 18,
    name: "Can You? Will You?",
    meaning: "Performance depends on ability and willingness.",
    example: "Before delegating, ask whether the employee can do it and will do it.",
    category: "Delegation & Management",
    trigger: "Use before delegating or assigning — diagnose both competence and motivation.",
    diagnosticQuestion: "Does this person have the ability to do this task AND the motivation to do it well?",
    relatedModels: [63, 60, 35, 136],
    comments: ""
  },
  {
    number: 19,
    name: "Change Curve",
    meaning: "Change typically causes a temporary dip before longer-term gains appear.",
    example: "Productivity falls briefly after an ERP go-live.",
    category: "Change Management",
    trigger: "Use when evaluating a change initiative — normalize the dip and plan for it rather than panicking.",
    diagnosticQuestion: "Are we in the expected dip phase, and have we planned for it rather than treating it as failure?",
    relatedModels: [20, 56, 12, 97],
    comments: ""
  },
  {
    number: 20,
    name: "Change Diamond",
    meaning: "Reduce change pain through ceremony, groups, pacing, and short-term low goals.",
    example: "Pilot by team, start with modest targets, and mark the transition visibly.",
    category: "Change Management",
    trigger: "Use when planning a change — design the transition deliberately to reduce resistance.",
    diagnosticQuestion: "Have I designed this change with ceremony, group support, appropriate pacing, and achievable early goals?",
    relatedModels: [19, 56, 12, 87],
    comments: ""
  },
  {
    number: 21,
    name: "Change Grid",
    meaning: "Managers and employees can view the same change very differently.",
    example: "Leadership sees a reorg as opportunity while staff sees it as disruption.",
    category: "Change Management",
    trigger: "Use when change communication is failing — map how different stakeholders perceive the same change.",
    diagnosticQuestion: "How do different stakeholder groups perceive this change, and have I communicated to each group's frame?",
    relatedModels: [97, 11, 122, 23],
    comments: ""
  },
  {
    number: 22,
    name: "Communication Cyber-Chart",
    meaning: "Communication is a multi-step process from sender perception to receiver action.",
    example: "Failure occurs not in sending the memo but in how it is decoded.",
    category: "Communication",
    trigger: "Use when a message has been sent but not acted on — trace where the communication broke down.",
    diagnosticQuestion: "At which step in the communication chain did the message break down?",
    relatedModels: [23, 34, 16, 77],
    comments: ""
  },
  {
    number: 23,
    name: "Communication Guidelines",
    meaning: "Communicate general to specific, simple to complex, known to unknown.",
    example: "Explain the overall policy first, then examples, then edge cases.",
    category: "Communication",
    trigger: "Use when structuring any important message — sequence from big picture to detail.",
    diagnosticQuestion: "Am I starting with the general context before diving into specifics?",
    relatedModels: [22, 64, 129, 149],
    comments: ""
  },
  {
    number: 24,
    name: "Compensation Fusion Triangle",
    meaning: "Compensation design must balance internal equity, external equity, and job performance.",
    example: "Market pay and individual results both matter when adjusting salary.",
    category: "Organization, Economics & Systems",
    trigger: "Use when designing or reviewing compensation — balance all three dimensions.",
    diagnosticQuestion: "Does this compensation decision balance what the market pays, what peers earn internally, and what this person contributes?",
    relatedModels: [25, 93, 118, 119],
    comments: ""
  },
  {
    number: 25,
    name: "Compensation Scale",
    meaning: "Contribution should align with compensation, using the 'five R's.'",
    example: "Pay decisions consider record, responsibilities, results, reward logic, and reference.",
    category: "Organization, Economics & Systems",
    trigger: "Use when making a pay decision — evaluate against all five dimensions.",
    diagnosticQuestion: "Have I weighed this person's record, responsibilities, results, reward logic, and market reference?",
    relatedModels: [24, 42, 93, 118],
    comments: ""
  },
  {
    number: 26,
    name: "Confidence Circle",
    meaning: "Confidence improves accomplishment, and accomplishment improves confidence.",
    example: "Giving a struggling rep one winnable account helps restore performance.",
    category: "Motivation & Behavior",
    trigger: "Use when someone is in a performance slump — create early wins to rebuild confidence.",
    diagnosticQuestion: "How can I create a small, winnable challenge that will rebuild this person's confidence?",
    relatedModels: [55, 83, 36, 123],
    comments: ""
  },
  {
    number: 27,
    name: "Connoisseur Effect",
    meaning: "Judgments are skewed by the best thing you have seen before.",
    example: "A manager underrates a good analyst because her last analyst was exceptional.",
    category: "Perception & Thinking",
    trigger: "Use when evaluating people or work — check for bias from previous exceptional comparisons.",
    diagnosticQuestion: "Am I rating this fairly, or am I comparing it to an unusually high previous benchmark?",
    relatedModels: [98, 150, 29, 122],
    comments: ""
  },
  {
    number: 28,
    name: "Control Diamond",
    meaning: "Effective control needs a standard, measurement system, measurement, and adjustment.",
    example: "An SLA dashboard is useless unless staffing changes follow the readings.",
    category: "Delegation & Management",
    trigger: "Use when a metric or standard exists but performance is not improving — check if all four control elements are present.",
    diagnosticQuestion: "Do we have a standard, a way to measure it, actual measurement, and a mechanism to adjust based on the reading?",
    relatedModels: [37, 138, 58, 71],
    comments: ""
  },
  {
    number: 29,
    name: "Critical Incident Procedure",
    meaning: "Evaluate with concrete incidents, not vague impressions.",
    example: "A review cites how the employee handled a customer crisis.",
    category: "Hiring, Training & Performance",
    trigger: "Use in performance reviews or evaluations — base all assessments on specific observable events.",
    diagnosticQuestion: "Can I cite a specific incident that demonstrates this evaluation, or am I relying on general impressions?",
    relatedModels: [42, 150, 138, 61],
    comments: ""
  },
  {
    number: 30,
    name: "Cruel Sea",
    meaning: "Some necessary decisions help the organization while harming some individuals.",
    example: "Consolidating two functions requires layoffs.",
    category: "Decision & Problem Solving",
    trigger: "Use when facing a decision that is right for the organization but harmful to individuals — acknowledge the tension honestly.",
    diagnosticQuestion: "Have I acknowledged and accounted for the human cost of this necessary decision?",
    relatedModels: [143, 116, 5, 120],
    comments: ""
  },
  {
    number: 31,
    name: "Decision Diamond",
    meaning: "Decisions draw on intuition, facts, experience, and policy.",
    example: "A pricing choice uses data, precedent, judgment, and rules.",
    category: "Decision & Problem Solving",
    trigger: "Use when making important decisions — ensure all four inputs are considered.",
    diagnosticQuestion: "Have I consulted my intuition, the relevant facts, my experience, and applicable policy?",
    relatedModels: [32, 78, 43, 130],
    comments: ""
  },
  {
    number: 32,
    name: "Decision Tree",
    meaning: "Solve by isolating the problem, generating alternatives, forecasting outcomes, and deciding.",
    example: "Vendor selection starts with clarifying the real requirement.",
    category: "Decision & Problem Solving",
    trigger: "Use when facing a complex decision — work through the problem systematically before choosing.",
    diagnosticQuestion: "Have I clearly defined the problem, identified real alternatives, and forecasted the outcomes of each?",
    relatedModels: [31, 37, 130, 126],
    comments: ""
  },
  {
    number: 33,
    name: "Define to Delegate",
    meaning: "You cannot delegate what you cannot define.",
    example: "A manager specifies scope, deadline, quality level, and decision rights before handoff.",
    category: "Delegation & Management",
    trigger: "Use before delegating any task — ensure the work is clearly defined first.",
    diagnosticQuestion: "Can I precisely define the scope, deadline, quality standard, and decision rights for this task?",
    relatedModels: [34, 35, 69, 9],
    comments: ""
  },
  {
    number: 34,
    name: "Delegation Cyber-Chart",
    meaning: "Delegation breaks when communication, competence, motivation, results, or information flow fail.",
    example: "The task is clear, but reporting checkpoints were never set.",
    category: "Delegation & Management",
    trigger: "Use when a delegation has failed — diagnose which link in the chain broke.",
    diagnosticQuestion: "Was the breakdown in communication, competence, motivation, results tracking, or information flow?",
    relatedModels: [33, 35, 22, 18],
    comments: ""
  },
  {
    number: 35,
    name: "Delegation Triangle",
    meaning: "Work can sit at do, do-report, or check-do-report.",
    example: "A trusted PM gets do-report authority for routine launches.",
    category: "Delegation & Management",
    trigger: "Use when calibrating how much autonomy to give — match the delegation level to the person's competence and trust.",
    diagnosticQuestion: "Should this person do it independently, do it and report, or have me check before they act?",
    relatedModels: [33, 34, 18, 82],
    comments: ""
  },
  {
    number: 36,
    name: "Desire for Change",
    meaning: "Motivation is fundamentally a desire for change.",
    example: "Coaching works only when the employee wants a better future state.",
    category: "Motivation & Behavior",
    trigger: "Use when a coaching or development effort is stalling — check if the person actually wants to change.",
    diagnosticQuestion: "Does this person genuinely want a different future state, or are they complying without real motivation?",
    relatedModels: [83, 87, 12, 55],
    comments: ""
  },
  {
    number: 37,
    name: "Deviation from Standard",
    meaning: "A problem is a gap from standard.",
    example: "Defect rate above target is the problem; the complaints are symptoms.",
    category: "Decision & Problem Solving",
    trigger: "Use when diagnosing a problem — identify the standard being violated rather than chasing symptoms.",
    diagnosticQuestion: "What is the standard that is being violated, and what is the measurable gap?",
    relatedModels: [28, 32, 112, 130],
    comments: ""
  },
  {
    number: 38,
    name: "Effectiveness – Right Things",
    meaning: "Effectiveness means focusing on the right priorities.",
    example: "Leadership stops chasing vanity metrics and centers on renewal rate.",
    category: "Planning & Priorities",
    trigger: "Use when evaluating whether activities are aligned to real objectives.",
    diagnosticQuestion: "Are the current activities actually the ones that matter most to achieving our objectives?",
    relatedModels: [39, 110, 4, 94],
    comments: ""
  },
  {
    number: 39,
    name: "Efficiency – Things Right",
    meaning: "Efficiency means doing the work with minimum waste.",
    example: "Automate the approved report instead of manually rebuilding it weekly.",
    category: "Planning & Priorities",
    trigger: "Use once the right activities are identified — then optimize execution.",
    diagnosticQuestion: "Are we doing the right work in the most waste-free way possible?",
    relatedModels: [38, 82, 1, 121],
    comments: ""
  },
  {
    number: 40,
    name: "Eighty Percent Rule",
    meaning: "In many business situations, 80 percent perfection is the economic optimum.",
    example: "Release the workable process, then improve it in use.",
    category: "Action & Execution",
    trigger: "Use when perfectionism is delaying delivery — determine if the cost of the last 20% exceeds its value.",
    diagnosticQuestion: "Is the remaining 20% of improvement worth the time and cost, or should we release and iterate?",
    relatedModels: [96, 80, 3, 143],
    comments: ""
  },
  {
    number: 41,
    name: "Encore Problem",
    meaning: "Future performance must equal or surpass prior performance.",
    example: "The team must top last year's blockbuster campaign.",
    category: "Motivation & Behavior",
    trigger: "Use when setting expectations after a great success — plan for the psychological pressure of topping it.",
    diagnosticQuestion: "Have I acknowledged the pressure of the encore and planned for it in goal-setting?",
    relatedModels: [119, 27, 98, 123],
    comments: ""
  },
  {
    number: 42,
    name: "Evaluation Fusion Triangle",
    meaning: "People are evaluated by traits, activities, and results.",
    example: "Review both behavior and output, not only final numbers.",
    category: "Hiring, Training & Performance",
    trigger: "Use in performance evaluation — ensure all three dimensions are assessed.",
    diagnosticQuestion: "Am I evaluating this person's traits, activities, and results, or focusing only on one dimension?",
    relatedModels: [29, 150, 60, 25],
    comments: ""
  },
  {
    number: 43,
    name: "Experience Paradox",
    meaning: "Managers have experience but often cannot retrieve it when needed.",
    example: "A veteran forgets a similar case during a fast-moving crisis.",
    category: "Perception & Thinking",
    trigger: "Use when building protocols or checklists — don't rely on memory alone even for experienced people.",
    diagnosticQuestion: "Have we documented this experience so it can be retrieved reliably, not just recalled when convenient?",
    relatedModels: [48, 78, 113, 31],
    comments: ""
  },
  {
    number: 44,
    name: "Failure Avoidance Selection",
    meaning: "Hiring is designed mainly to avoid failure.",
    example: "Selection screens filter out risk but also filter out upside.",
    category: "Hiring, Training & Performance",
    trigger: "Use when reviewing a hiring process — check if it optimizes only for safety or also for potential.",
    diagnosticQuestion: "Is our selection process filtering out only failures or also filtering out high-upside candidates?",
    relatedModels: [136, 61, 75, 54],
    comments: ""
  },
  {
    number: 45,
    name: "Fallacy of Composition",
    meaning: "Because B follows A does not mean A caused B.",
    example: "Sales rose after a town hall, but the real driver was a product release.",
    category: "Perception & Thinking",
    trigger: "Use when attributing causation — check if the correlation is real or coincidental.",
    diagnosticQuestion: "Is there evidence of causation here, or just correlation?",
    relatedModels: [37, 32, 131, 5],
    comments: ""
  },
  {
    number: 46,
    name: "Flyspeck Management",
    meaning: "Major and minor issues receive nearly equal attention.",
    example: "The executive rewrites formatting while ignoring margin erosion.",
    category: "Delegation & Management",
    trigger: "Use when evaluating management focus — are high-impact issues getting disproportionate attention?",
    diagnosticQuestion: "Am I spending time proportional to the importance of each issue?",
    relatedModels: [38, 95, 110, 4],
    comments: ""
  },
  {
    number: 47,
    name: "Freudian Hydraulic",
    meaning: "Pressure can trigger psychologically unpredictable reactions.",
    example: "A blunt performance talk produces an unexpectedly emotional resignation.",
    category: "Motivation & Behavior",
    trigger: "Use before delivering high-stakes feedback — anticipate unpredictable emotional responses.",
    diagnosticQuestion: "What unexpected emotional reactions might this pressure or message trigger?",
    relatedModels: [115, 6, 8, 100],
    comments: ""
  },
  {
    number: 48,
    name: "Fugitive Information",
    meaning: "Information exists but cannot be retrieved in time or at reasonable cost.",
    example: "The lesson learned is buried in a folder no one can find during an outage.",
    category: "Organization, Economics & Systems",
    trigger: "Use when information systems are failing — check if knowledge exists but is inaccessible.",
    diagnosticQuestion: "Does the needed information exist somewhere, and what prevents it from being retrieved in time?",
    relatedModels: [43, 113, 58, 66],
    comments: ""
  },
  {
    number: 49,
    name: "Good Subordinate",
    meaning: "A 'good subordinate' is partly a boss-defined category.",
    example: "One supervisor loves what another sees as insufficient initiative.",
    category: "Delegation & Management",
    trigger: "Use when evaluating an employee transfer or reassignment — what the current boss sees may not transfer.",
    diagnosticQuestion: "Is my evaluation of this person based on objective performance or on how well they fit my preferred style?",
    relatedModels: [27, 54, 60, 150],
    comments: ""
  },
  {
    number: 50,
    name: "Hawthorne Effect",
    meaning: "Performance may improve temporarily simply because people know something is being done or watched.",
    example: "A pilot KPI spikes during the first month of attention.",
    category: "Perception & Thinking",
    trigger: "Use when interpreting early results from a change or program — account for the observation effect.",
    diagnosticQuestion: "Are these early results driven by the intervention itself or by the awareness of being observed?",
    relatedModels: [51, 45, 28, 19],
    comments: ""
  },
  {
    number: 51,
    name: "Heisenberg Principle",
    meaning: "Measurement itself changes behavior.",
    example: "Agents alter conduct once they know calls are actively scored.",
    category: "Perception & Thinking",
    trigger: "Use when designing metrics — anticipate that measuring something will change the behavior it measures.",
    diagnosticQuestion: "How will the act of measuring this change the behavior we're trying to observe?",
    relatedModels: [50, 28, 90, 14],
    comments: ""
  },
  {
    number: 52,
    name: "Help Philosophy",
    meaning: "A manager is most effective when seen as someone who helps people succeed.",
    example: "The leader removes blockers instead of only policing compliance.",
    category: "Delegation & Management",
    trigger: "Use when assessing management effectiveness — is the manager helping or just supervising?",
    diagnosticQuestion: "Am I removing obstacles and enabling success, or primarily monitoring and enforcing?",
    relatedModels: [72, 71, 55, 129],
    comments: ""
  },
  {
    number: 53,
    name: "History Fusion Triangle",
    meaning: "Big events can be read through challenge-response, great-person, and dialectic lenses.",
    example: "A strategy review considers market shock, leadership choices, and structural tension.",
    category: "Decision & Problem Solving",
    trigger: "Use when analyzing why something happened — look through multiple interpretive lenses.",
    diagnosticQuestion: "What were the external challenges, the key leadership decisions, and the underlying structural tensions?",
    relatedModels: [31, 32, 78, 45],
    comments: ""
  },
  {
    number: 54,
    name: "Identification",
    meaning: "The manager's first job is finding who can successfully do the job.",
    example: "Assign a turnaround to the operator with proven fit under current conditions.",
    category: "Hiring, Training & Performance",
    trigger: "Use before assigning a critical role — match the person to the specific situation, not just the general job description.",
    diagnosticQuestion: "Who has the specific skills, attitude, and experience for this particular situation?",
    relatedModels: [61, 60, 75, 136],
    comments: ""
  },
  {
    number: 55,
    name: "Improvement Diagram",
    meaning: "Desire for improvement is influenced through leadership and standards.",
    example: "Combine manager coaching with visible performance expectations.",
    category: "Motivation & Behavior",
    trigger: "Use when trying to improve performance — ensure both leadership coaching and clear standards are present.",
    diagnosticQuestion: "Are both the leadership support and the performance standards clear enough to drive improvement?",
    relatedModels: [36, 26, 63, 72],
    comments: ""
  },
  {
    number: 56,
    name: "Incrementalism",
    meaning: "Change works better when introduced in manageable steps.",
    example: "Phase in pricing rules by region instead of changing every market at once.",
    category: "Change Management",
    trigger: "Use when planning a major change — design it in phases to reduce risk and resistance.",
    diagnosticQuestion: "Can this change be broken into smaller, sequenced steps to reduce disruption?",
    relatedModels: [20, 19, 80, 12],
    comments: ""
  },
  {
    number: 57,
    name: "Indispensable Person",
    meaning: "Someone the organization cannot afford to lose.",
    example: "Only one payroll specialist understands the legacy structure.",
    category: "Organization, Economics & Systems",
    trigger: "Use when assessing organizational risk — identify single points of failure in people.",
    diagnosticQuestion: "Who is indispensable, and what is the risk if they leave tomorrow?",
    relatedModels: [66, 92, 48, 121],
    comments: ""
  },
  {
    number: 58,
    name: "Info-Action Diagram",
    meaning: "Management converts information input into action output.",
    example: "Service backlog data is processed into a staffing change.",
    category: "Delegation & Management",
    trigger: "Use when information exists but no action is taken — trace the gap between data and decision.",
    diagnosticQuestion: "Is the information being received, processed, and converted into action?",
    relatedModels: [28, 73, 22, 48],
    comments: ""
  },
  {
    number: 59,
    name: "Interview Pentagon",
    meaning: "A complete interview covers job, self, others, company, and compensation.",
    example: "A panel uses the same five-part sequence for every finalist.",
    category: "Hiring, Training & Performance",
    trigger: "Use when preparing for or conducting an interview — ensure all five areas are covered.",
    diagnosticQuestion: "Have I covered all five areas: the job, the candidate's self-assessment, working with others, company fit, and compensation?",
    relatedModels: [61, 54, 117, 44],
    comments: ""
  },
  {
    number: 60,
    name: "Job Fusion Triangle",
    meaning: "Job performance depends on the person, the situation, and others.",
    example: "The same employee thrives in one team context and struggles in another.",
    category: "Hiring, Training & Performance",
    trigger: "Use when diagnosing poor performance — look beyond the person to the situation and team dynamics.",
    diagnosticQuestion: "Is the performance issue in the person, the situation, or the dynamics with others?",
    relatedModels: [61, 42, 18, 54],
    comments: ""
  },
  {
    number: 61,
    name: "Job Match Diagram",
    meaning: "Hiring is about fit between person and role.",
    example: "A strong analyst is mismatched in a hunter-sales position.",
    category: "Hiring, Training & Performance",
    trigger: "Use in any hiring or reassignment decision — evaluate person-role fit explicitly.",
    diagnosticQuestion: "Does this person's skills, style, and motivation match what this specific role actually requires?",
    relatedModels: [60, 54, 18, 44],
    comments: ""
  },
  {
    number: 62,
    name: "Job Organization Chain",
    meaning: "A job has a history formed by each predecessor.",
    example: "Recurring handoff failures belong to the role design, not just the current occupant.",
    category: "Organization, Economics & Systems",
    trigger: "Use when a role keeps failing — examine whether the problem is systemic rather than personal.",
    diagnosticQuestion: "Is this performance problem a person issue or a role design issue inherited from predecessors?",
    relatedModels: [60, 37, 134, 62],
    comments: ""
  },
  {
    number: 63,
    name: "KASH Formula",
    meaning: "Improvement requires knowledge, attitude, skills, and habits.",
    example: "Sales training adds product knowledge but also call discipline and belief.",
    category: "Hiring, Training & Performance",
    trigger: "Use when diagnosing underperformance — identify which of the four elements is deficient.",
    diagnosticQuestion: "Is this a knowledge gap, an attitude problem, a skill gap, or a habit issue?",
    relatedModels: [18, 60, 101, 145],
    comments: ""
  },
  {
    number: 64,
    name: "Ladder of Abstraction",
    meaning: "Ideas can be moved from very concrete to very general.",
    example: "'Late shipment' is raised to 'service reliability' for planning.",
    category: "Communication",
    trigger: "Use when bridging tactical problems to strategic conversations, or vice versa.",
    diagnosticQuestion: "At what level of abstraction should this be discussed to solve it most effectively?",
    relatedModels: [23, 32, 103, 37],
    comments: ""
  },
  {
    number: 65,
    name: "Logic Box",
    meaning: "Existing KASH limits what people can perceive and imagine.",
    example: "A technical team cannot see a commercial solution outside its frame.",
    category: "Perception & Thinking",
    trigger: "Use when teams are stuck — check if their KASH is limiting what solutions they can see.",
    diagnosticQuestion: "Is our knowledge, attitude, skills, or habits preventing us from seeing a solution that exists outside our current framework?",
    relatedModels: [7, 99, 63, 122],
    comments: ""
  },
  {
    number: 66,
    name: "Mack Truck Theory",
    meaning: "Any person can be lost at any time.",
    example: "Cross-train before the lone subject-matter expert resigns.",
    category: "Organization, Economics & Systems",
    trigger: "Use in succession planning or knowledge management — identify who would leave a critical gap if lost suddenly.",
    diagnosticQuestion: "Who are we most dependent on, and what have we done to reduce that dependency?",
    relatedModels: [57, 92, 48, 121],
    comments: ""
  },
  {
    number: 67,
    name: "Macro-Economic System",
    meaning: "Markets work through linked public, business, factor, and goods/services flows.",
    example: "Wage pressure eventually shows up in pricing decisions.",
    category: "Organization, Economics & Systems",
    trigger: "Use when analyzing business environment — trace systemic economic connections.",
    diagnosticQuestion: "What macro-economic forces are flowing into this situation?",
    relatedModels: [91, 103, 121, 24],
    comments: ""
  },
  {
    number: 68,
    name: "Magic Hand",
    meaning: "Dependence on another person produces ambivalent feelings toward that person.",
    example: "A founder depends on a strong operator yet resents the dependence.",
    category: "Motivation & Behavior",
    trigger: "Use when a key relationship feels strained despite strong performance — look for dependence-driven ambivalence.",
    diagnosticQuestion: "Is the tension in this relationship driven by dependence rather than actual performance issues?",
    relatedModels: [6, 57, 74, 85],
    comments: ""
  },
  {
    number: 69,
    name: "Main Event Compass",
    meaning: "Action requires deciding what, when, where, how, who, and why.",
    example: "A rollout plan is weak when it has tasks but no owner or rationale.",
    category: "Planning & Priorities",
    trigger: "Use when a plan is missing critical elements — check that every action has all six components.",
    diagnosticQuestion: "Does this plan specify what, when, where, how, who, and why for every key action?",
    relatedModels: [33, 104, 126, 71],
    comments: ""
  },
  {
    number: 70,
    name: "Main Event Principle",
    meaning: "Unless things change, they stay the same.",
    example: "Service quality will not improve merely because leadership demands improvement.",
    category: "Action & Execution",
    trigger: "Use when improvement is expected without structural change — identify what specifically must change.",
    diagnosticQuestion: "What specific change will actually produce a different outcome?",
    relatedModels: [2, 3, 90, 55],
    comments: ""
  },
  {
    number: 71,
    name: "Management Definition",
    meaning: "Management is accomplishing predetermined objectives through others.",
    example: "The manager's job is to orchestrate execution, not to be the lone hero.",
    category: "Delegation & Management",
    trigger: "Use when evaluating whether someone is managing or just doing — management means results through others.",
    diagnosticQuestion: "Are results coming through effective orchestration of others, or through individual contribution?",
    relatedModels: [17, 52, 73, 94],
    comments: ""
  },
  {
    number: 72,
    name: "Management Gap",
    meaning: "Output improves when subordinates believe the manager can and will help them achieve objectives.",
    example: "Trust falls when escalations disappear into silence.",
    category: "Delegation & Management",
    trigger: "Use when team performance is lagging — check if employees believe in the manager's ability and willingness to help.",
    diagnosticQuestion: "Do my team members believe I have the ability and intention to help them succeed?",
    relatedModels: [52, 55, 107, 71],
    comments: ""
  },
  {
    number: 73,
    name: "Management Process Cyber-Chart",
    meaning: "Management is a repeatable flow process from information through action toward objectives.",
    example: "A weekly operating review follows the same information-to-decision pipeline.",
    category: "Delegation & Management",
    trigger: "Use when building management systems — design repeatable processes from information to decision to action.",
    diagnosticQuestion: "Is there a reliable pipeline from information intake to decision to action, or are steps skipped?",
    relatedModels: [58, 28, 71, 104],
    comments: ""
  },
  {
    number: 74,
    name: "Management Smog",
    meaning: "A manager feels threatened by a more competent subordinate.",
    example: "A director withholds exposure from a rising star.",
    category: "Delegation & Management",
    trigger: "Use when a high-performer is being underutilized — check if management insecurity is the real cause.",
    diagnosticQuestion: "Is this person being held back by the organization's needs or by a manager's insecurity?",
    relatedModels: [68, 81, 107, 92],
    comments: ""
  },
  {
    number: 75,
    name: "Manager Selection Diamond",
    meaning: "Organizations use several common patterns to select managers.",
    example: "They promote the best operator without testing actual managerial fit.",
    category: "Hiring, Training & Performance",
    trigger: "Use when selecting a manager — evaluate managerial fit specifically, not just technical performance.",
    diagnosticQuestion: "Is this person being selected for managerial ability, or just technical performance in an individual role?",
    relatedModels: [102, 54, 61, 44],
    comments: ""
  },
  {
    number: 76,
    name: "Marketing Fusion Triangle",
    meaning: "Market success depends on product/service, channel, and market working together.",
    example: "A strong offer fails because it is sold through the wrong channel.",
    category: "Organization, Economics & Systems",
    trigger: "Use when a marketing effort is underperforming — check alignment across all three elements.",
    diagnosticQuestion: "Is the product/service, channel, and target market fully aligned?",
    relatedModels: [103, 91, 67, 121],
    comments: ""
  },
  {
    number: 77,
    name: "Marriage-Type Communication",
    meaning: "Frequent communicators develop shorthand that outsiders may not understand.",
    example: "Founder conversations are efficient for insiders and confusing for new leaders.",
    category: "Communication",
    trigger: "Use when onboarding new people or expanding teams — surface implicit assumptions and jargon.",
    diagnosticQuestion: "What shorthand or unspoken assumptions exist in our communication that newcomers won't understand?",
    relatedModels: [22, 16, 23, 149],
    comments: ""
  },
  {
    number: 78,
    name: "Meaningful Experience",
    meaning: "Experience matters most when direct, visible, and understood.",
    example: "Personally running a major incident teaches more than hearing a briefing about one.",
    category: "Hiring, Training & Performance",
    trigger: "Use in training design — prioritize direct, visible, understood experience over passive learning.",
    diagnosticQuestion: "Is this learning experience direct, visible to the learner, and explicitly connected to meaning?",
    relatedModels: [43, 149, 101, 146],
    comments: ""
  },
  {
    number: 79,
    name: "MEM Wheel",
    meaning: "MEM is intended as an integrated system influencing decisions broadly.",
    example: "Course models and management systems reinforce each other.",
    category: "Organization, Economics & Systems",
    trigger: "Use when designing a management system — ensure models and practices reinforce each other.",
    diagnosticQuestion: "Are the management tools and models in use reinforcing each other or contradicting each other?",
    relatedModels: [73, 71, 103, 88],
    comments: ""
  },
  {
    number: 80,
    name: "Minimum Commitment Rule",
    meaning: "Commit the minimum resources required in most business situations.",
    example: "Run a pilot before funding a companywide rollout.",
    category: "Planning & Priorities",
    trigger: "Use before committing major resources — find the smallest test that can validate the concept.",
    diagnosticQuestion: "What is the minimum commitment needed to test this adequately before full commitment?",
    relatedModels: [56, 40, 91, 143],
    comments: ""
  },
  {
    number: 81,
    name: "Mobility Circle",
    meaning: "Mobility improves competence, and competence improves mobility.",
    example: "A tough rotation prepares someone for broader promotion.",
    category: "Hiring, Training & Performance",
    trigger: "Use in talent development — create stretch assignments to build both skills and career options.",
    diagnosticQuestion: "What challenging rotation or assignment would build this person's competence and expand their opportunities?",
    relatedModels: [92, 74, 26, 63],
    comments: ""
  },
  {
    number: 82,
    name: "More Time Cyber-Chart",
    meaning: "More time comes from spending, simplifying, pre-delegating, and delegating.",
    example: "Standardize work and shift decisions downward.",
    category: "Delegation & Management",
    trigger: "Use when a leader is overwhelmed — identify what can be simplified, pre-decided, or delegated.",
    diagnosticQuestion: "What tasks can I eliminate, simplify, pre-decide, or delegate to free up time for high-priority work?",
    relatedModels: [35, 94, 142, 39],
    comments: ""
  },
  {
    number: 83,
    name: "Motivation – Dissatisfaction",
    meaning: "Motivation arises from dissatisfaction with the present state.",
    example: "A missed promotion finally triggers deliberate development.",
    category: "Motivation & Behavior",
    trigger: "Use when trying to motivate someone — identify the gap between current reality and desired state.",
    diagnosticQuestion: "What present-state dissatisfaction can I help this person see to motivate meaningful change?",
    relatedModels: [36, 84, 87, 55],
    comments: ""
  },
  {
    number: 84,
    name: "Motivation Stair-Steps",
    meaning: "People seek to satisfy needs in ascending levels.",
    example: "A team worried about job security will not care much about self-actualizing project work.",
    category: "Motivation & Behavior",
    trigger: "Use when a motivational approach is failing — check if lower-level needs are unmet.",
    diagnosticQuestion: "Are basic security and belonging needs met before expecting engagement with higher-order motivators?",
    relatedModels: [83, 85, 8, 26],
    comments: ""
  },
  {
    number: 85,
    name: "Motivation Triangle",
    meaning: "Motivation can be read through security, stimulation, and identity needs.",
    example: "A role redesign fails because it removes identity even though it adds challenge.",
    category: "Motivation & Behavior",
    trigger: "Use when designing roles or incentives — ensure security, stimulation, and identity needs are met.",
    diagnosticQuestion: "Does this role or change satisfy security, stimulation, and identity needs?",
    relatedModels: [84, 83, 8, 120],
    comments: ""
  },
  {
    number: 86,
    name: "No-Cost Consultant",
    meaning: "A consultant is effectively 'no cost' if benefits exceed fees.",
    example: "A lean specialist saves more waste than the engagement costs.",
    category: "Organization, Economics & Systems",
    trigger: "Use when evaluating external expertise — frame the decision as ROI, not cost.",
    diagnosticQuestion: "Will the benefits of this expertise exceed its cost?",
    relatedModels: [91, 5, 137, 80],
    comments: ""
  },
  {
    number: 87,
    name: "North Wind Theory",
    meaning: "Create desire for change instead of trying to force it.",
    example: "Show salespeople how the new system helps them close deals faster.",
    category: "Change Management",
    trigger: "Use when a change is meeting resistance — frame it in terms of what's in it for the people involved.",
    diagnosticQuestion: "How can I make this change desirable to the people who need to adopt it?",
    relatedModels: [36, 12, 97, 83],
    comments: ""
  },
  {
    number: 88,
    name: "Northbound Train",
    meaning: "Organizations need a clear, shared directional philosophy.",
    example: "Strategy, rewards, and language all point in the same direction.",
    category: "Organization, Economics & Systems",
    trigger: "Use when assessing organizational alignment — check that all systems point the same direction.",
    diagnosticQuestion: "Are strategy, incentives, language, and culture all pointing the same direction?",
    relatedModels: [79, 103, 151, 76],
    comments: ""
  },
  {
    number: 89,
    name: "Obsolescence Fusion Triangle",
    meaning: "Obsolescence reflects style, function, and quality.",
    example: "A product can become obsolete even while still physically working.",
    category: "Organization, Economics & Systems",
    trigger: "Use when evaluating products, roles, or processes — check for all three dimensions of obsolescence.",
    diagnosticQuestion: "Is this obsolete in style, in function, or in quality?",
    relatedModels: [76, 91, 67, 121],
    comments: ""
  },
  {
    number: 90,
    name: "Operant Conditioning",
    meaning: "Consequences shape future behavior.",
    example: "Tying bonuses to renewal rates shifts behavior toward retention.",
    category: "Motivation & Behavior",
    trigger: "Use when designing incentive or performance systems — what behaviors are being rewarded or punished?",
    diagnosticQuestion: "What behaviors are the current consequences reinforcing?",
    relatedModels: [14, 51, 70, 55],
    comments: ""
  },
  {
    number: 91,
    name: "Opportunity Cost",
    meaning: "Using resources one way sacrifices a better alternative.",
    example: "Keeping engineers on internal reporting delays revenue-producing features.",
    category: "Decision & Problem Solving",
    trigger: "Use in resource allocation decisions — always ask what you're giving up.",
    diagnosticQuestion: "What is the best alternative use of these resources that we're forgoing?",
    relatedModels: [143, 121, 1, 38],
    comments: ""
  },
  {
    number: 92,
    name: "Opportunity Wedge",
    meaning: "Time narrows horizons and options.",
    example: "Delayed reskilling leaves fewer career options later.",
    category: "Planning & Priorities",
    trigger: "Use when deciding whether to invest in development — the window of opportunity closes over time.",
    diagnosticQuestion: "Is the window for this opportunity closing, and what will I lose if I wait?",
    relatedModels: [66, 81, 57, 3],
    comments: ""
  },
  {
    number: 93,
    name: "Organization Fusion Triangle",
    meaning: "Rewards and privileges usually reflect some mix of merit, heredity, and equality.",
    example: "Promotions combine performance, tenure, and internal politics.",
    category: "Organization, Economics & Systems",
    trigger: "Use when analyzing reward decisions — what mix of merit, seniority, and politics is driving them?",
    diagnosticQuestion: "What is the actual basis for this reward decision: merit, seniority, or political factors?",
    relatedModels: [24, 25, 118, 134],
    comments: ""
  },
  {
    number: 94,
    name: "Organizing Pie",
    meaning: "Decide what you should do yourself before delegating the rest.",
    example: "A leader keeps critical stakeholder calls and delegates dashboard maintenance.",
    category: "Delegation & Management",
    trigger: "Use when planning your time — identify what requires your direct involvement before delegating.",
    diagnosticQuestion: "What tasks require my unique skills or authority, and which can be delegated?",
    relatedModels: [82, 33, 71, 38],
    comments: ""
  },
  {
    number: 95,
    name: "Pareto's Law",
    meaning: "A small share of causes usually drives a large share of effects.",
    example: "The top few defects generate most complaints.",
    category: "Decision & Problem Solving",
    trigger: "Use when prioritizing problems — identify the vital few causes behind the majority of effects.",
    diagnosticQuestion: "Which 20% of causes are driving 80% of the outcomes?",
    relatedModels: [38, 46, 110, 37],
    comments: ""
  },
  {
    number: 96,
    name: "Parkinson's Laws",
    meaning: "Work expands to fill available time, and spending rises to meet income.",
    example: "A loose deadline produces unnecessary complexity.",
    category: "Planning & Priorities",
    trigger: "Use when setting deadlines or budgets — create appropriate constraints to prevent waste.",
    diagnosticQuestion: "Are deadlines and budgets tight enough to prevent unnecessary expansion of scope?",
    relatedModels: [142, 40, 3, 80],
    comments: ""
  },
  {
    number: 97,
    name: "People Resist Change??",
    meaning: "People do not resist all change; they resist being changed and some specific changes.",
    example: "Staff welcome a tool they helped select.",
    category: "Change Management",
    trigger: "Use when a change faces resistance — diagnose whether resistance is to change itself or to the specific change.",
    diagnosticQuestion: "Are people resisting change generically or this specific change, and have they had any input?",
    relatedModels: [87, 12, 20, 11],
    comments: ""
  },
  {
    number: 98,
    name: "Perceptual Fraction",
    meaning: "Perception depends on an item's relation to other items.",
    example: "5 percent growth feels weak when competitors grew 12 percent.",
    category: "Perception & Thinking",
    trigger: "Use when evaluating performance — ensure comparisons are made against appropriate benchmarks.",
    diagnosticQuestion: "What is the appropriate reference point for evaluating this performance?",
    relatedModels: [27, 118, 50, 45],
    comments: ""
  },
  {
    number: 99,
    name: "Perceptual 'K-H'",
    meaning: "People see only what they know how to see.",
    example: "A novice misses a compliance pattern obvious to an experienced auditor.",
    category: "Perception & Thinking",
    trigger: "Use when assessing expertise or diagnosing blind spots — what training is needed to see what's already there?",
    diagnosticQuestion: "What knowledge or training would help this person see what they are currently missing?",
    relatedModels: [65, 15, 27, 78],
    comments: ""
  },
  {
    number: 100,
    name: "Personality Change Methods",
    meaning: "Deep adult personality change is difficult and rare.",
    example: "Do not build a role around hoping a chronic controller becomes naturally empowering soon.",
    category: "Hiring, Training & Performance",
    trigger: "Use when facing a performance issue that requires personality change — consider whether the role can be redesigned instead.",
    diagnosticQuestion: "Is this a skills/knowledge gap I can address with training, or a personality trait I need to work around?",
    relatedModels: [63, 60, 47, 101],
    comments: ""
  },
  {
    number: 101,
    name: "PESOS Formula",
    meaning: "Train skills by preparing, explaining, showing, observing, and supervising.",
    example: "Teach machine setup with demonstration and checked practice, not lecture alone.",
    category: "Hiring, Training & Performance",
    trigger: "Use when designing skills training — follow the full PESOS sequence for effective transfer.",
    diagnosticQuestion: "Does this training include preparation, explanation, demonstration, observed practice, and supervised follow-up?",
    relatedModels: [63, 145, 78, 146],
    comments: ""
  },
  {
    number: 102,
    name: "Peter Principle",
    meaning: "People tend to get promoted to their level of incompetence.",
    example: "The best seller becomes a weak sales manager.",
    category: "Hiring, Training & Performance",
    trigger: "Use in promotion decisions — assess fit for the new role specifically, not performance in the current role.",
    diagnosticQuestion: "Is this person being promoted based on performance in the current role or on predicted fit in the new role?",
    relatedModels: [75, 61, 54, 44],
    comments: ""
  },
  {
    number: 103,
    name: "Planning Fusion Triangle",
    meaning: "Plans require strategic, tactical, and operational decisions.",
    example: "Expansion requires target market choice, staffing plan, and day-to-day execution detail.",
    category: "Planning & Priorities",
    trigger: "Use when building a plan — check that all three levels are addressed.",
    diagnosticQuestion: "Does this plan address strategic direction, tactical choices, and operational execution?",
    relatedModels: [104, 105, 88, 69],
    comments: ""
  },
  {
    number: 104,
    name: "Planning Path",
    meaning: "A plan needs present position, objectives, action program, timetable, obstacles, and alternatives.",
    example: "A transformation roadmap without obstacles or backups is incomplete.",
    category: "Planning & Priorities",
    trigger: "Use when critiquing or building a plan — check for all six elements.",
    diagnosticQuestion: "Does this plan address current position, objectives, actions, timeline, obstacles, and contingencies?",
    relatedModels: [103, 105, 69, 130],
    comments: ""
  },
  {
    number: 105,
    name: "Planning Pentagon",
    meaning: "Objectives can be set from competitor results, organizational results, resources, opportunities, and shareholder expectations.",
    example: "Annual planning balances ambition with actual capacity.",
    category: "Planning & Priorities",
    trigger: "Use in goal-setting — ensure objectives are grounded in all five sources.",
    diagnosticQuestion: "Are these objectives informed by competition, past results, available resources, opportunities, and stakeholder expectations?",
    relatedModels: [103, 104, 38, 121],
    comments: ""
  },
  {
    number: 106,
    name: "Polishing Action",
    meaning: "Workplace education often refines more than reconstructs people.",
    example: "Onboarding usually sharpens existing professional habits rather than remaking personality.",
    category: "Hiring, Training & Performance",
    trigger: "Use when designing onboarding or training — focus on refining existing strengths rather than rebuilding from scratch.",
    diagnosticQuestion: "What existing strengths can training build on, rather than what needs to be replaced?",
    relatedModels: [63, 100, 78, 145],
    comments: ""
  },
  {
    number: 107,
    name: "Power Bank Account",
    meaning: "Superior-subordinate relationships draw on several power sources.",
    example: "Expert power may persuade more effectively than formal authority.",
    category: "Delegation & Management",
    trigger: "Use when needing to influence without direct authority — identify which power source is most appropriate.",
    diagnosticQuestion: "Which source of power—expert, referent, positional, reward, or coercive—is most appropriate here?",
    relatedModels: [108, 72, 52, 13],
    comments: ""
  },
  {
    number: 108,
    name: "Power Diamond",
    meaning: "Power is used through both personal and institutional sources.",
    example: "A leader combines credibility with formal decision rights.",
    category: "Delegation & Management",
    trigger: "Use when assessing influence effectiveness — leverage both personal credibility and institutional authority.",
    diagnosticQuestion: "Am I using both my personal credibility and my institutional authority effectively?",
    relatedModels: [107, 72, 52, 13],
    comments: ""
  },
  {
    number: 109,
    name: "Price to Stay",
    meaning: "The cost of keeping a role equals the cost of getting it.",
    example: "The director role continues to require travel and role conflict after promotion.",
    category: "Motivation & Behavior",
    trigger: "Use when someone is considering a promotion or new role — make the ongoing costs explicit.",
    diagnosticQuestion: "What is the ongoing price of staying in this role, not just the cost of getting there?",
    relatedModels: [120, 85, 30, 143],
    comments: ""
  },
  {
    number: 110,
    name: "Priority Triangle",
    meaning: "Classify work into must do, should do, and nice to do.",
    example: "During an outage, backlog grooming drops to 'nice to do.'",
    category: "Planning & Priorities",
    trigger: "Use when work is overwhelming — classify everything into must, should, and nice-to-do buckets.",
    diagnosticQuestion: "Is this work truly a must-do, a should-do, or a nice-to-do?",
    relatedModels: [38, 4, 95, 96],
    comments: ""
  },
  {
    number: 111,
    name: "Problem Avoidance",
    meaning: "Preventing problems is a core management responsibility.",
    example: "A pre-mortem catches launch risks before they become incidents.",
    category: "Decision & Problem Solving",
    trigger: "Use in planning phases — actively look for what can go wrong before it does.",
    diagnosticQuestion: "What problems can I prevent by acting now rather than responding later?",
    relatedModels: [140, 130, 104, 32],
    comments: ""
  },
  {
    number: 112,
    name: "Problem Filter",
    meaning: "People mainly see problems they know how to solve or can no longer ignore.",
    example: "A chronic issue is ignored until it reaches crisis level.",
    category: "Perception & Thinking",
    trigger: "Use when reviewing what problems are being addressed — check for blind spots in what's being noticed.",
    diagnosticQuestion: "What problems are being ignored because they fall outside our expertise or tolerance?",
    relatedModels: [37, 99, 7, 65],
    comments: ""
  },
  {
    number: 113,
    name: "Progress Principle",
    meaning: "Progress comes through correcting error and writing history.",
    example: "Each postmortem ends with a playbook update.",
    category: "Action & Execution",
    trigger: "Use when building learning systems — ensure errors are captured and converted into institutional knowledge.",
    diagnosticQuestion: "Are we systematically capturing errors and converting them into updated playbooks?",
    relatedModels: [48, 43, 78, 111],
    comments: ""
  },
  {
    number: 114,
    name: "Promotion Jettison",
    meaning: "Advancement requires giving up old duties.",
    example: "The new manager stops handling every key customer personally.",
    category: "Delegation & Management",
    trigger: "Use when someone is struggling after promotion — check if they have let go of their former role.",
    diagnosticQuestion: "Has this person fully given up their previous duties to take on the new ones?",
    relatedModels: [35, 71, 102, 94],
    comments: ""
  },
  {
    number: 115,
    name: "Psychic Radar",
    meaning: "Good leaders read attitudes and reactions in live interaction.",
    example: "A negotiator sees hesitation before the objection is spoken.",
    category: "Communication",
    trigger: "Use when reading a room — develop sensitivity to unspoken signals during interactions.",
    diagnosticQuestion: "What unspoken signals am I receiving about this person's true feelings or intentions?",
    relatedModels: [47, 6, 122, 29],
    comments: ""
  },
  {
    number: 116,
    name: "Pyrrhic Victory",
    meaning: "A win that costs more than it is worth.",
    example: "Forcing a low-margin deal damages the account and exhausts the team.",
    category: "Decision & Problem Solving",
    trigger: "Use before pursuing a win aggressively — calculate the full cost of winning.",
    diagnosticQuestion: "What is the full cost of winning here, and does it exceed the value of the win?",
    relatedModels: [5, 30, 91, 143],
    comments: ""
  },
  {
    number: 117,
    name: "Recruiting Diamond",
    meaning: "Recruiting follows picture, locate, compare, and sell.",
    example: "Define the talent picture before sourcing candidates.",
    category: "Hiring, Training & Performance",
    trigger: "Use when starting a search — define the profile before sourcing.",
    diagnosticQuestion: "Do we have a clear picture of the ideal candidate before we start looking?",
    relatedModels: [54, 61, 59, 44],
    comments: ""
  },
  {
    number: 118,
    name: "Relative Deprivation",
    meaning: "People feel deprived when actual conditions fall short of the standard they compare against.",
    example: "A raise disappoints after peers receive more.",
    category: "Motivation & Behavior",
    trigger: "Use when managing expectations around rewards — people will compare to peers, not just to history.",
    diagnosticQuestion: "What reference group will this person compare against, and will this feel fair by that standard?",
    relatedModels: [98, 119, 24, 93],
    comments: ""
  },
  {
    number: 119,
    name: "Rising Expectations",
    meaning: "Expectations tend to outpace achievement.",
    example: "Last year's bonus quickly becomes this year's minimum acceptable outcome.",
    category: "Motivation & Behavior",
    trigger: "Use when managing recognition or reward programs — plan for escalating expectations.",
    diagnosticQuestion: "How will expectations change after this reward or achievement, and am I prepared for that shift?",
    relatedModels: [118, 41, 83, 98],
    comments: ""
  },
  {
    number: 120,
    name: "Roles and Goals",
    meaning: "Life creates tension between duties and ambitions.",
    example: "A high-potential manager declines relocation because of family-role priorities.",
    category: "Motivation & Behavior",
    trigger: "Use in career conversations — acknowledge the tension between role obligations and personal ambitions.",
    diagnosticQuestion: "What role obligations are competing with this person's career goals?",
    relatedModels: [85, 109, 30, 7],
    comments: ""
  },
  {
    number: 121,
    name: "Scarce Resources",
    meaning: "Manpower, money, machines, methods, and materials are limited.",
    example: "Engineering time cannot be spent on both platform reliability and every new feature.",
    category: "Organization, Economics & Systems",
    trigger: "Use in any resource allocation decision — acknowledge scarcity explicitly.",
    diagnosticQuestion: "Which scarce resource is the binding constraint here?",
    relatedModels: [91, 143, 80, 38],
    comments: ""
  },
  {
    number: 122,
    name: "Selective Perception",
    meaning: "People see selectively through physical and mental filters.",
    example: "Operations hears 'cost control' where product hears 'innovation cut.'",
    category: "Perception & Thinking",
    trigger: "Use when messages are being misinterpreted — identify the filters distorting reception.",
    diagnosticQuestion: "What filters are causing different people to hear this message differently?",
    relatedModels: [15, 99, 11, 131],
    comments: ""
  },
  {
    number: 123,
    name: "Self-Fulfilling Prophecy",
    meaning: "People behave partly according to what they think others expect of them.",
    example: "Low expectations from a manager depress a junior analyst's confidence.",
    category: "Motivation & Behavior",
    trigger: "Use in people management — be aware of how expectations communicated to others shape their performance.",
    diagnosticQuestion: "What expectations am I projecting, and how might they be shaping this person's behavior?",
    relatedModels: [26, 55, 90, 41],
    comments: ""
  },
  {
    number: 124,
    name: "Seven Ports of Life",
    meaning: "Review life by where time is spent across seven domains.",
    example: "A burnout diagnosis shows health and recreation have been squeezed out.",
    category: "Motivation & Behavior",
    trigger: "Use in coaching or career conversations — explore the full balance of life domains.",
    diagnosticQuestion: "Which life domains are being neglected and contributing to burnout or dissatisfaction?",
    relatedModels: [125, 85, 120, 7],
    comments: ""
  },
  {
    number: 125,
    name: "Seven Ports of Management",
    meaning: "Organizational reputation is judged by seven stakeholder groups.",
    example: "A plant decision is reviewed not only for customers but also for employees, government, and community.",
    category: "Organization, Economics & Systems",
    trigger: "Use when making major decisions — consider impact across all stakeholder groups.",
    diagnosticQuestion: "How will this decision affect each of the seven stakeholder groups?",
    relatedModels: [124, 30, 88, 76],
    comments: ""
  },
  {
    number: 126,
    name: "Six Honest Servingmen",
    meaning: "Analyze by asking what, where, when, how, why, and who.",
    example: "A defect review uses every question before solutions are proposed.",
    category: "Decision & Problem Solving",
    trigger: "Use when analyzing any problem — ensure all six analytical angles are covered.",
    diagnosticQuestion: "Have I answered what, where, when, how, why, and who before proposing solutions?",
    relatedModels: [32, 69, 37, 53],
    comments: ""
  },
  {
    number: 127,
    name: "Slot Machine Management",
    meaning: "Frequent massive changes create instability.",
    example: "The org chart changes every quarter in search of a miracle fix.",
    category: "Change Management",
    trigger: "Use when evaluating change frequency — distinguish productive evolution from destabilizing churn.",
    diagnosticQuestion: "Is this change creating stability or adding to a pattern of destabilizing turbulence?",
    relatedModels: [56, 19, 20, 79],
    comments: ""
  },
  {
    number: 128,
    name: "So What? What If?",
    meaning: "Test consequences and contingencies.",
    example: "Before a cut, ask what it means and what happens if assumptions fail.",
    category: "Decision & Problem Solving",
    trigger: "Use when evaluating decisions — stress test the consequences and failure scenarios.",
    diagnosticQuestion: "So what does this mean, and what if our key assumptions are wrong?",
    relatedModels: [32, 104, 130, 31],
    comments: ""
  },
  {
    number: 129,
    name: "Socratic Method",
    meaning: "Teach or coach through carefully guided questions.",
    example: "A manager leads the analyst to the root cause instead of telling the answer.",
    category: "Communication",
    trigger: "Use when coaching — guide discovery through questions rather than providing answers.",
    diagnosticQuestion: "What question could I ask that would guide this person to discover the answer themselves?",
    relatedModels: [52, 55, 23, 101],
    comments: ""
  },
  {
    number: 130,
    name: "Solution Pentagon",
    meaning: "Solutions can be corrective, adaptive, interim, contingency, or preventive.",
    example: "Crisis response uses a workaround now and a preventive fix later.",
    category: "Decision & Problem Solving",
    trigger: "Use when responding to a problem — choose the right type of solution for the situation.",
    diagnosticQuestion: "Is the right response corrective, adaptive, interim, contingency, or preventive?",
    relatedModels: [32, 111, 37, 31],
    comments: ""
  },
  {
    number: 131,
    name: "Stimulus Discrimination",
    meaning: "Distinguish differences after classifying incoming information.",
    example: "An experienced reviewer separates a one-off complaint from a meaningful pattern.",
    category: "Perception & Thinking",
    trigger: "Use when evaluating data or feedback — distinguish signal from noise.",
    diagnosticQuestion: "Is this information a meaningful signal or noise, and what distinguishes it from similar cases?",
    relatedModels: [133, 132, 99, 37],
    comments: ""
  },
  {
    number: 132,
    name: "Stimulus Fraction",
    meaning: "New information is processed through the total store of prior experience.",
    example: "The same feedback lands differently with a veteran than with a new hire.",
    category: "Perception & Thinking",
    trigger: "Use when delivering feedback — consider how the recipient's experience will filter your message.",
    diagnosticQuestion: "How will this person's prior experience shape how they receive this information?",
    relatedModels: [131, 133, 15, 99],
    comments: ""
  },
  {
    number: 133,
    name: "Stimulus Generalization",
    meaning: "Incoming information is grouped into subject and value categories.",
    example: "An agent instantly buckets a case as 'billing' before deeper diagnosis.",
    category: "Perception & Thinking",
    trigger: "Use when people are jumping to categorize too quickly — check for premature classification.",
    diagnosticQuestion: "Are we grouping this in the right category, or jumping to a classification that prevents deeper analysis?",
    relatedModels: [131, 132, 122, 10],
    comments: ""
  },
  {
    number: 134,
    name: "Suboptimization",
    meaning: "A sub-unit optimizes its own goal at the expense of the whole.",
    example: "A warehouse maximizes pick speed while accuracy collapses.",
    category: "Organization, Economics & Systems",
    trigger: "Use when a team is performing well locally but harming the whole — check for misaligned incentives.",
    diagnosticQuestion: "Is this unit optimizing its own metric at the expense of the broader organizational objective?",
    relatedModels: [93, 88, 90, 62],
    comments: ""
  },
  {
    number: 135,
    name: "Substandard Performance Alternatives",
    meaning: "The logical options are upgrade, transfer, or termination.",
    example: "Coach first, reassign second, separate if necessary.",
    category: "Hiring, Training & Performance",
    trigger: "Use when someone is chronically underperforming — make an explicit decision between the three options.",
    diagnosticQuestion: "Have I exhausted upgrading and transferring options before considering termination?",
    relatedModels: [141, 63, 60, 100],
    comments: ""
  },
  {
    number: 136,
    name: "Success Oriented Selection",
    meaning: "Hiring is designed to achieve success, not merely avoid failure.",
    example: "A growth unit hires for upside potential, not only safety.",
    category: "Hiring, Training & Performance",
    trigger: "Use when hiring for a growth or stretch role — design the process around finding upside potential.",
    diagnosticQuestion: "Is our selection process identifying high-potential candidates or just filtering out risk?",
    relatedModels: [44, 54, 61, 117],
    comments: ""
  },
  {
    number: 137,
    name: "Sunk Cost",
    meaning: "Irrecoverable past cost should be written off in future decisions.",
    example: "Stop the failing project despite the money already spent.",
    category: "Decision & Problem Solving",
    trigger: "Use when continuing a failing initiative — remove past investment from the decision calculus.",
    diagnosticQuestion: "Am I continuing this because it's the right path forward, or because of what was already spent?",
    relatedModels: [91, 5, 116, 128],
    comments: ""
  },
  {
    number: 138,
    name: "Supervision Fusion Triangle",
    meaning: "Supervisory judgment should use records, observations, and interviews.",
    example: "Do not rely on dashboards alone; walk the floor and talk to people.",
    category: "Delegation & Management",
    trigger: "Use when supervising — triangulate between data, direct observation, and conversations.",
    diagnosticQuestion: "Am I using all three sources: records, observations, and direct conversations?",
    relatedModels: [28, 29, 42, 138],
    comments: ""
  },
  {
    number: 139,
    name: "Synergism Diagram",
    meaning: "Management skill determines how far output can move from normal to maximum productivity.",
    example: "The same headcount produces more under better coordination.",
    category: "Delegation & Management",
    trigger: "Use when evaluating management quality — measure by how far the team performs above its baseline.",
    diagnosticQuestion: "How much above baseline is this team producing, and what management practices drive that gap?",
    relatedModels: [71, 73, 52, 17],
    comments: ""
  },
  {
    number: 140,
    name: "The Gun",
    meaning: "Avoid creating problems just so you can later 'solve' them; problem avoidance matters.",
    example: "Stop last-minute approval drama that leadership itself created.",
    category: "Action & Execution",
    trigger: "Use when diagnosing recurring problems — check if leadership behavior is creating the problems it claims to solve.",
    diagnosticQuestion: "Is this problem being created or maintained by the same people who are trying to solve it?",
    relatedModels: [111, 3, 70, 46],
    comments: ""
  },
  {
    number: 141,
    name: "Three-Step Termination",
    meaning: "Define the problem, agree a corrective program, and agree the consequences.",
    example: "A PIP clearly states the gap, the remedy, and the result of failure.",
    category: "Hiring, Training & Performance",
    trigger: "Use when managing to a consequence — ensure all three steps are explicit and agreed.",
    diagnosticQuestion: "Have the performance gap, the required remedy, and the consequence of failure all been clearly defined and agreed?",
    relatedModels: [135, 29, 37, 63],
    comments: ""
  },
  {
    number: 142,
    name: "Tomato Plant Problem",
    meaning: "Work overload exceeds the time available.",
    example: "A leader with too many approvals becomes the bottleneck.",
    category: "Planning & Priorities",
    trigger: "Use when a leader is overwhelmed — identify what needs to be pruned or delegated.",
    diagnosticQuestion: "What can be pruned, delegated, or eliminated to prevent this bottleneck?",
    relatedModels: [82, 96, 4, 94],
    comments: ""
  },
  {
    number: 143,
    name: "Trade-Off Principle",
    meaning: "Every action means some other action cannot be taken.",
    example: "Faster launch means less customization or less testing.",
    category: "Decision & Problem Solving",
    trigger: "Use in any resource or scope decision — explicitly name the trade-off.",
    diagnosticQuestion: "What are we giving up by choosing this, and have we explicitly accepted that trade-off?",
    relatedModels: [91, 121, 30, 5],
    comments: ""
  },
  {
    number: 144,
    name: "Training Diamond",
    meaning: "Training effectiveness depends on trainer, trainee, subject matter, and method.",
    example: "Expert content fails when presented with poor method.",
    category: "Hiring, Training & Performance",
    trigger: "Use when evaluating a training failure — check all four dimensions, not just content.",
    diagnosticQuestion: "Is the training failing because of the trainer, trainee readiness, subject matter design, or delivery method?",
    relatedModels: [101, 145, 78, 63],
    comments: ""
  },
  {
    number: 145,
    name: "Training Formula",
    meaning: "Training closes the gap between needed KASH and current KASH.",
    example: "Onboarding maps which product, attitude, skill, and habit gaps must be closed.",
    category: "Hiring, Training & Performance",
    trigger: "Use when designing training — explicitly map the KASH gap before designing the intervention.",
    diagnosticQuestion: "What is the specific knowledge, attitude, skills, and habits gap that training must close?",
    relatedModels: [63, 101, 144, 106],
    comments: ""
  },
  {
    number: 146,
    name: "Training Fusion Triangle",
    meaning: "Learning comes from formal, on-the-job, and informal training.",
    example: "Workshop, shadowing, and peer coaching all matter.",
    category: "Hiring, Training & Performance",
    trigger: "Use when designing learning — balance formal programs with on-the-job and informal learning.",
    diagnosticQuestion: "Does our learning strategy include formal, on-the-job, and informal learning elements?",
    relatedModels: [101, 144, 78, 145],
    comments: ""
  },
  {
    number: 147,
    name: "Two Tragedies",
    meaning: "There are two goal tragedies: not reaching the goal and reaching it.",
    example: "A founder hits the exit target and then loses purpose.",
    category: "Motivation & Behavior",
    trigger: "Use in goal-setting — plan for what comes after the goal, not just how to reach it.",
    diagnosticQuestion: "What will replace the meaning and motivation that achieving this goal currently provides?",
    relatedModels: [85, 83, 120, 41],
    comments: ""
  },
  {
    number: 148,
    name: "Two Tyrannies",
    meaning: "Two unavoidable forces are that others will judge you and things will change.",
    example: "A redesign must accept both scrutiny and instability.",
    category: "Action & Execution",
    trigger: "Use when someone is resisting judgment or change — acknowledge these as constants, not exceptions.",
    diagnosticQuestion: "Are we designing this to handle both external judgment and ongoing change?",
    relatedModels: [97, 8, 19, 70],
    comments: ""
  },
  {
    number: 149,
    name: "Verbal/Extensional Worlds",
    meaning: "People live in both direct experience and the world described by others.",
    example: "Classroom explanation plus field experience together build judgment.",
    category: "Communication",
    trigger: "Use in training or communication design — balance explanation with direct experience.",
    diagnosticQuestion: "Are we relying too much on verbal description when direct experience would be more effective?",
    relatedModels: [78, 23, 132, 101],
    comments: ""
  },
  {
    number: 150,
    name: "X Is Good",
    meaning: "Unsupported evaluations are opinions, not facts.",
    example: "'She is not strategic' must be tied to observable evidence.",
    category: "Communication",
    trigger: "Use when evaluating or giving feedback — require behavioral evidence for any assessment.",
    diagnosticQuestion: "What observable evidence supports this evaluation?",
    relatedModels: [29, 42, 138, 15],
    comments: ""
  },
  {
    number: 151,
    name: "Yes Concept",
    meaning: "Performance improves when people broadly agree with strategy and tactics.",
    example: "A strategy rollout succeeds because managers and staff are aligned on the approach.",
    category: "Change Management",
    trigger: "Use when planning an initiative — build alignment before launching.",
    diagnosticQuestion: "Do the people who need to execute this genuinely agree with and support this approach?",
    relatedModels: [87, 97, 88, 12],
    comments: ""
  }
];

// Spaced repetition intervals (in days)
const SR_INTERVALS = {
  missed: 0,    // Review same day
  hard: 1,
  got_it: 3,
  easy: 7
};

// Interval multipliers for repeat correct answers
const SR_MULTIPLIERS = {
  missed: 0.5,
  hard: 0.8,
  got_it: 1.5,
  easy: 2.0
};

// Initialize mastery data
function initializeMastery() {
  return {
    level: 0,
    lastReviewed: null,
    nextReview: new Date().toISOString().split('T')[0],
    correct: 0,
    incorrect: 0,
    interval: 0,
    easeFactor: 2.5
  };
}

export { MODELS, CATEGORIES, SR_INTERVALS, SR_MULTIPLIERS, initializeMastery };
